name: aseprite-win-nsi
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        enable_ui: [on]
        include:
          - os: windows-latest
            build_type: Release
            enable_ui: on
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        if: runner.os == 'Linux'
        with:
          key: ${{ matrix.os }}-${{ matrix.enable_ui }}
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - name: Generating Makefiles
        shell: bash
        run: |
          export enable_ccache=off
          curl -L https://github.com/blueloveTH/aseprite/releases/download/v0.01/skia.zip --output skia.zip
          curl -L https://github.com/blueloveTH/aseprite/releases/download/v0.01/libcrypto-1_1-x64.dll --output libcrypto-1_1-x64.dll
          7z x skia.zip
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DENABLE_UI=${{ matrix.enable_ui }} \
            -DENABLE_CCACHE=$enable_ccache \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=./skia \
            -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 \
            -DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib
      - name: Print Absolute Build Path and Directory Structure
        shell: powershell
        run: |
          Write-Host "Absolute path of build directory:"
          $absolutePath = (Resolve-Path build).Path
          Write-Host $absolutePath
          Write-Host "Build directory structure:"
          Get-ChildItem -Path $absolutePath -Recurse | Format-Table -AutoSize
      - name: Compiling
        shell: bash
        run: |
          cd build && ninja
      - name: Install NSIS
        run: |
          choco install nsis
      - name: Build Windows Installer
        run: |
          makensis aseprite.nsi
      - uses: actions/upload-artifact@v4
        with:
          name: Aseprite-v1.3.13-Win
          path: D:\a\aseprite-v1.3.13\aseprite-v1.3.13\Aseprite-v1.3.13.exe
