name: aseprite-mac
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        build_type: [Release]
        enable_ui: [on]
        include:
          - os: macos-latest
            build_type: Release
            enable_ui: on
    steps:
      - uses: actions/checkout@master
        with:
          submodules: "recursive"
      - name: Print Xcode Path
        run: |
          xcode_path=$(xcode-select -p)
          echo "Xcode Path: $xcode_path"
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'MacOS'
      - name: Generating Mac Package
        shell: bash
        run: |
          export enable_ccache=off
          curl -L https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-macOS-Release-x64.zip --output Skia-macOS-Release-x64.zip
          7z x Skia-macOS-Release-x64.zip -o./skia
          ls -lh ./skia
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_OSX_ARCHITECTURES=x86_64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 \
            -DCMAKE_OSX_SYSROOT=/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=./skia \
            -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 \
            -DSKIA_LIBRARY=./skia/out/Release-x64/libskia.a \
            -G Ninja \
      - name: Print Absolute Build Path and Directory Structure
        shell: bash
        run: |
          echo "Absolute path of build directory:"
          cd build
          pwd
          echo "Build directory structure:"
          ls -al
      - name: Compiling
        shell: bash
        run: |
          cd build && ninja
      - name: Create .app bundle
        run: |
          mkdir -p ./pack/Aseprite.app/Contents/MacOS
          mkdir -p ./pack/Aseprite.app/Contents/Resources
          curl -o ./pack/Aseprite.app/Contents/Resources/Aseprite.icns "https://hcmall-oss.oss-cn-shenzhen.aliyuncs.com/aseprite/Aseprite.icns"
          curl -o ./pack/Aseprite.app/Contents/Resources/Document.icns "https://hcmall-oss.oss-cn-shenzhen.aliyuncs.com/aseprite/Document.icns"
          curl -o ./pack/Aseprite.app/Contents/Resources/Extension.icns "https://hcmall-oss.oss-cn-shenzhen.aliyuncs.com/aseprite/Extension.icns"
          cp ./build/bin/aseprite ./pack/Aseprite.app/Contents/MacOS/aseprite
          cp -R ./build/bin/data ./pack/Aseprite.app/Contents/Resources/data
          echo "APPL????" > ./pack/Aseprite.app/Contents/PkgInfo
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
                <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
                <plist version=\"1.0\">
                  <dict>
                    <key>CFBundleDocumentTypes</key>
                    <array>
                      <dict>
                        <key>CFBundleTypeExtensions</key>
                        <array>
                          <string>aseprite</string>
                        </array>
                        <key>CFBundleTypeIconFile</key>
                        <string>Document.icns</string>
                        <key>CFBundleTypeName</key>
                        <string>Aseprite Sprite</string>
                        <key>CFBundleTypeRole</key>
                        <string>Editor</string>
                        <key>LSHandlerRank</key>
                        <string>Owner</string>
                      </dict>
                      <dict>
                        <key>CFBundleTypeExtensions</key>
                        <array>
                          <string>ase</string>
                          <string>bmp</string>
                          <string>flc</string>
                          <string>fli</string>
                          <string>gif</string>
                          <string>ico</string>
                          <string>jpeg</string>
                          <string>jpg</string>
                          <string>pcx</string>
                          <string>png</string>
                          <string>tga</string>
                        </array>
                        <key>CFBundleTypeIconFile</key>
                        <string>Document.icns</string>
                        <key>CFBundleTypeName</key>
                        <string>Aseprite Sprite</string>
                        <key>CFBundleTypeRole</key>
                        <string>Editor</string>
                      </dict>
                      <dict>
                        <key>CFBundleTypeExtensions</key>
                        <array>
                          <string>aseprite-extension</string>
                        </array>
                        <key>CFBundleTypeIconFile</key>
                        <string>Extension.icns</string>
                        <key>CFBundleTypeName</key>
                        <string>Aseprite Extension</string>
                        <key>CFBundleTypeRole</key>
                        <string>Editor</string>
                        <key>LSHandlerRank</key>
                        <string>Owner</string>
                      </dict>
                    </array>
                    <key>CFBundleDisplayName</key>
                    <string>Aseprite-v1.3.13</string>
                    <key>CFBundleExecutable</key>
                    <string>aseprite</string>
                    <key>CFBundleIdentifier</key>
                    <string>org.aseprite.Aseprite</string>
                    <key>CFBundleName</key>
                    <string>Aseprite</string>
                    <key>CFBundlePackageType</key>
                    <string>APPL</string>
                    <key>CFBundleInfoDictionaryVersion</key>
                    <string>6.0</string>
                    <key>CFBundleShortVersionString</key>
                    <string>1.3.13</string>
                    <key>CFBundleVersion</key>
                    <string>1.3.13</string>
                    <key>CFBundleIconFile</key>
                    <string>Aseprite.icns</string>
                    <key>LSApplicationCategoryType</key>
                    <string>public.app-category.graphics-design</string>
                    <key>NSHumanReadableCopyright</key>
                    <string>Copyright © 2001-2024, Igara Studio S.A. All rights reserved.</string>
                    <key>NSHighResolutionCapable</key>
                    <true/>
                    <key>NSRequiresAquaSystemAppearance</key>
                    <false/>
                  </dict>
                </plist>" > ./pack/Aseprite.app/Contents/info.plist
      - name: Create DMG
        run: |
          npm install --global create-dmg
          create-dmg ./pack/Aseprite.app ./pack
          mv "Aseprite-v1.3.13 1.3.13.dmg" "Aseprite-v1.3.13(x64).dmg"
        continue-on-error: true
      - name: List contents of ./pack directory
        run: ls ./pack
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-v1.3.13-MacOS-x64
          path: |
            ./pack/Aseprite*.dmg
